apiVersion: 1

groups:
  - name: TestAlerts
    folder: Tests
    interval: 10s
    rules:
      - uid: test_alert_001
        title: Test Alert
        condition: C
        data:
          - refId: A
            datasourceUid: prometheus
            queryType: range
            relativeTimeRange:
              from: 3600
              to: 0
            model:
              expr: 'test_metric'
              instant: false
              range: true
              refId: A
          - refId: B
            datasourceUid: prometheus
            queryType: range
            relativeTimeRange:
              from: 3600
              to: 0
            model:
              expr: 'test_metric'
              instant: false
              range: true
              refId: B
          - refId: C
            relativeTimeRange:
              from: 3600
              to: 0
            model:
              type: threshold
              datasource:
                type: __expr__
                uid: __expr__
              conditions:
                - evaluator:
                    params:
                      - 3
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - B
                  reducer:
                    type: avg
                  type: query
        for: 10s
        annotations:
          summary: Test alert triggered
          description: "This is a test alert"
        labels:
          severity: info
          team: test